// @ts-check
/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 * */
module.exports = {
  myAutogeneratedSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // '.' 即当前的文档文件夹
    },
  ],
};
